### ISSUE TITLE
fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by ibeckermayer** [cloudflare/boring#164]
When trying to compile a project which uses

```toml
boring = { version = "2.1.0", features = ["fips"], optional = true }
```

I hit the following error:

```
The following warnings were emitted during compilation:

warning: fetching boringssl git submodule

error: failed to run custom build command for `boring-sys v2.1.0`
note: To improve backtraces for build dependencies, set the CARGO_PROFILE_TEST_BUILD_OVERRIDE_DEBUG=true environment variable to enable debug information generation.

Caused by:
  process didn't exit successfully: `/Users/ibeckermayer/gravitational/teleport/target/debug/build/boring-sys-00449934e380ee8c/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=BORING_BSSL_PATH
  cargo:warning=fetching boringssl git submodule

  --- stderr
  fatal: not a git repository (or any of the parent directories): .git
  thread 'main' panicked at 'failed to fetch submodule - consider running `git submodule update --init --recursive deps/boringssl` yourself', /Users/ibeckermayer/.cargo/registry/src/index.crates.io-6f17d22bba15001f/boring-sys-2.1.0/build.rs:325:17
  stack backtrace:
     0: std::panicking::begin_panic
               at /rustc/90c541806f23a127002de5b4038be731ba1458ca/library/std/src/panicking.rs:610:12
     1: build_script_build::main::{{closure}}
     2: core::result::Result<T,E>::unwrap_or_else
     3: build_script_build::main
     4: core::ops::function::FnOnce::call_once
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
warning: build failed, waiting for other jobs to finish...
```

**Comment by nox** [comment]
boring 3 is out.
