### ISSUE TITLE
failed to run custom build command for `boring-sys v4.10.2` (Windows 11 WSL2 arch linux)

### ISSUE THREAD

**Issue by sylann** [cloudflare/boring#283]
Similar issues:
- https://github.com/cloudflare/boring/issues/242
- https://github.com/cloudflare/boring/issues/121

The output to STDERR is:

```
cargo run
   Compiling boring-sys v4.10.2
error: failed to run custom build command for `boring-sys v4.10.2`

Caused by:
  process didn't exit successfully: `/home/archbtw/avisto/tcm/backend/target/debug/build/boring-sys-21189a854ea148ad/build-script-main` (exit status: 101)
  --- stdout

  ... building logs ...

  --- stderr

  thread 'main' panicked at /home/archbtw/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bindgen-0.70.1/lib.rs:622:27:
  Unable to find libclang: "couldn't find any valid shared libraries matching: ['libclang.so', 'libclang-*.so', 'libclang.so.*', 'libclang-*.so.*'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This line seems odd:
> "where one of these files can be found (invalid: [])"

**System information**:
- The computer is a Windows 11 Pro.
- The build is executed on WSL2 (Arch Linux, variant of my company).

I don't install boring-sys directly, it is an indirect dependency of jwt-simple.
```
jwt-simple v0.12.10
├── boring v4.10.2
    ├── boring-sys v4.10.2
```

**Comment by elonaire** [comment]
@sylann I am facing the same issue, I have to downgrade for now

**Comment by bill-habermaas** [comment]
Compiles and builds on macOS sequoia. project runs successful but error occurs when building docker image.

**Comment by tcortega** [comment]
I've tried everything to make it work so far and nothing works.

Tried installing `mingw64`, `msys2`, setting up the `C_INCLUDE_PATH`, `CC`, `CXX`, `CPLUS_INCLUDE_PATH`, and `LIBRARY_PATH` variables, installing `LLVM`.

**Comment by rushilmehra** [comment]
> Compiles and builds on macOS sequoia. project runs successful but error occurs when building docker image.
> 
> ## thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/boring-sys-4.16.0/build/main.rs:574:44:
> 27.43 called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
> 27.43 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 27.43 warning: build failed, waiting for other jobs to finish...

This is somethig wrong with applying patches during bulid time. If you can open a separate issue with more details on how you're building then I can take a look

**Comment by rushilmehra** [comment]
Where is LLVM installed on your system? And what is `LIBRARY_PATH` set to?

**Comment by Asenlan** [comment]
You need to download LLVM  and Set the LIBCLANG_PATH environment variable to your LLVM binary path: D:\\LLVM\\bin

**Comment by rushilmehra** [comment]
Oh yeah I meant `LIBCLANG_PATH` not `LIBRARY_PATH`

**Comment by bill-habermaas** [comment]
This problem is on macOS, not windows

**Comment by 0x676e67** [comment]
I suspect that your docker mirror has not been installed with git, so it can't initialize the build source code directory. You should give a detailed compilation environment, which will help us solve the problem. Instead of just giving an error log. In this way, no one knows what happened to you.

**Comment by bill-habermaas** [comment]
I installed LLVM for macOS and see the same problem.
27.63   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/boring-sys-4.16.0/build/main.rs:574:44:
27.63   called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
27.63   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
27.63 warning: build failed, waiting for other jobs to finish...

I can build and run the rust project. I just cannot build a docker image.

**Comment by bill-habermaas** [comment]
I have created a simple project that demonstrates the error and created a repo for it on GitHub.
It is public and found at https://github.com/bill-habermaas/jwt-playtime1.

**Comment by 0x676e67** [comment]
on ubuntu/debian
```bash
sudo apt-get install build-essential cmake perl pkg-config libclang-dev musl-tools git -y

cargo build --release
```

**Comment by bill-habermaas** [comment]
installing cmake does not fix the issue.  There is no problem except when building a docker image.  

cargo build --release makes no difference.

**Comment by rushilmehra** [comment]
Have you tried installing git? Please install all packages listed by @0x676e67 in the message above

**Comment by 0x676e67** [comment]
> installing cmake does not fix the issue. There is no problem except when building a docker image.安装 cmake 并不能解决问题。除了构建 docker 镜像时，其他都没有问题。
> 
> cargo build --release makes no difference.cargo build --release 没有什么区别。

I told you it was just an example, did you install git? Why didn't you follow the advice...

**Comment by bill-habermaas** [comment]
thanks for the Dockerfile. The build worked.

**Comment by LevitatingBusinessMan** [comment]
> on ubuntu/debian
> 
> sudo apt-get install build-essential cmake perl pkg-config libclang-dev musl-tools git -y
> 
> cargo build --release

You also need `git`
