### ISSUE TITLE
DTLS Acceptor.accept() panics: source slice length (169) does not match destination slice length (16717)

### ISSUE THREAD

**Issue by rainerschoe** [cloudflare/boring#38]
Hi, I am trying to build an DTLS server, however boring crate panics inside `acceptor.accept(client)`:
```
> RUST_BACKTRACE=full ./server
Hello, world!
new client 127.0.0.1:3400
thread '<unnamed>' panicked at 'source slice length (169) does not match destination slice length (16717)', /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3052:13
stack backtrace:
   0:     0x55d2ce8caa30 - std::backtrace_rs::backtrace::libunwind::trace::h1037ca7e6eeef65c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x55d2ce8caa30 - std::backtrace_rs::backtrace::trace_unsynchronized::haaefac1bc3669450
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55d2ce8caa30 - std::sys_common::backtrace::_print_fmt::h863a6f5e6d995885
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55d2ce8caa30 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h767e17e1aa7df6a8
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55d2ce8e5fcc - core::fmt::write::h7aa6cd0067dca82a
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/fmt/mod.rs:1110:17
   5:     0x55d2ce8c5945 - std::io::Write::write_fmt::h4c802b6f761026c1
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/io/mod.rs:1590:15
   6:     0x55d2ce8cc9bb - std::sys_common::backtrace::_print::h2769edb26a7eb606
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55d2ce8cc9bb - std::sys_common::backtrace::print::ha71f3549862b4cb6
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55d2ce8cc9bb - std::panicking::default_hook::{{closure}}::h95488a3bade217f6
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:208:50
   9:     0x55d2ce8cc491 - std::panicking::default_hook::h290aa602c0fb11df
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:225:9
  10:     0x55d2ce8cd061 - std::panicking::rust_panic_with_hook::hf32c4fa635e215f2
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:622:17
  11:     0x55d2ce8ccb67 - std::panicking::begin_panic_handler::{{closure}}::h95197ccd88846f7a
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:519:13
  12:     0x55d2ce8caf0c - std::sys_common::backtrace::__rust_end_short_backtrace::h7641df9566f7b7d0
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x55d2ce8ccac9 - rust_begin_unwind
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:515:5
  14:     0x55d2ce66a611 - core::panicking::panic_fmt::hbe99dddd3092ba3c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/panicking.rs:92:14
  15:     0x55d2ce66a8e2 - core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail::h5656d919d719ae34
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3045:13
  16:     0x55d2ce797816 - core::slice::<impl [T]>::copy_from_slice::h74e194cebb1b8af1
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3052:13
  17:     0x55d2ce67b52e - <[T] as core::slice::CloneFromSpec<T>>::spec_clone_from::ha7a1ef94c0af3f73
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:3511:9
  18:     0x55d2ce67b4fd - core::slice::<impl [T]>::clone_from_slice::h47a286f3d99a55e9
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/slice/mod.rs:2976:9
  19:     0x55d2ce67f968 - <server::Client as std::io::Read>::read::h0de8f8a9217a3f33
                               at /home/rainer/projects/svpn/src/bin/server.rs:33:9
  20:     0x55d2ce6859aa - boring::ssl::bio::bread::{{closure}}::hfd992d9656758214
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-1.1.6/src/ssl/bio.rs:132:44
  21:     0x55d2ce691e03 - core::ops::function::FnOnce::call_once::h0c06a9ec110e984c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/ops/function.rs:227:5
  22:     0x55d2ce68cf4b - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc4091e66dd5678d8
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:346:9
  23:     0x55d2ce697817 - std::panicking::try::do_call::h57a17334329a61c2
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:401:40
  24:     0x55d2ce697fad - __rust_try
  25:     0x55d2ce6972cf - std::panicking::try::h64fe1f6863686bdf
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:365:19
  26:     0x55d2ce68cfca - std::panic::catch_unwind::h0d7f78bdb190c068
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:433:14
  27:     0x55d2ce685734 - boring::ssl::bio::bread::h82aafe50cf15d0fd
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-1.1.6/src/ssl/bio.rs:132:11
  28:     0x55d2ce7a072f - BIO_read
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/crypto/bio/bio.c:136:13
  29:     0x55d2ce81adfd - dtls_read_buffer_next_packet
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/ssl/ssl_buffer.cc:136:15
  30:     0x55d2ce81b046 - _ZN4bssl25ssl_read_buffer_extend_toEP6ssl_stm
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/ssl/ssl_buffer.cc:194:39
  31:     0x55d2ce81b12e - _ZN4bssl22ssl_handle_open_recordEP6ssl_stPbNS_17ssl_open_record_tEmh
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/ssl/ssl_buffer.cc:222:47
  32:     0x55d2ce884ffa - _ZN4bssl17ssl_run_handshakeEPNS_13SSL_HANDSHAKEEPb
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/ssl/handshake.cc:608:45
  33:     0x55d2ce821bc3 - SSL_do_handshake
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/ssl/ssl_lib.cc:888:30
  34:     0x55d2ce821c7e - SSL_accept
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-sys-1.1.1/deps/boringssl/src/ssl/ssl_lib.cc:919:26
  35:     0x55d2ce67e531 - boring::ssl::SslStreamBuilder<S>::accept::hd54d648559981c40
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-1.1.6/src/ssl/mod.rs:3267:28
  36:     0x55d2ce67e7bf - boring::ssl::Ssl::accept::h3966736b4a85d5f9
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-1.1.6/src/ssl/mod.rs:2190:9
  37:     0x55d2ce68cd5a - boring::ssl::connector::SslAcceptor::accept::h6a9e2413c5d55c76
                               at /home/rainer/.cargo/registry/src/github.com-1ecc6299db9ec823/boring-1.1.6/src/ssl/connector.rs:286:9
  38:     0x55d2ce6875ed - server::main::{{closure}}::{{closure}}::h2ba642e4b7547cbe
                               at /home/rainer/projects/svpn/src/bin/server.rs:194:30
  39:     0x55d2ce67e950 - std::sys_common::backtrace::__rust_begin_short_backtrace::hca503e22ee861ef0
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys_common/backtrace.rs:125:18
  40:     0x55d2ce66e8cc - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h2ddb3d53624470ae
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/thread/mod.rs:481:17
  41:     0x55d2ce68cee0 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::ha3fa15a26594939c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:346:9
  42:     0x55d2ce697a37 - std::panicking::try::do_call::he5a67af5ef45f393
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:401:40
  43:     0x55d2ce697fad - __rust_try
  44:     0x55d2ce697541 - std::panicking::try::h85d02fc31b27ff88
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panicking.rs:365:19
  45:     0x55d2ce68d090 - std::panic::catch_unwind::h527d9841e5377c0e
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/panic.rs:433:14
  46:     0x55d2ce66e6e0 - std::thread::Builder::spawn_unchecked::{{closure}}::h895b5611edd2eed1
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/thread/mod.rs:480:30
  47:     0x55d2ce691d3e - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1139201a4c7b5fff
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/core/src/ops/function.rs:227:5
  48:     0x55d2ce8d0207 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h902e2cf6655e1b0c
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/alloc/src/boxed.rs:1575:9
  49:     0x55d2ce8d0207 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h893a5452154309d1
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/alloc/src/boxed.rs:1575:9
  50:     0x55d2ce8d0207 - std::sys::unix::thread::Thread::new::thread_start::hdedcb57c96ab37cd
                               at /rustc/f64503eb555475d65ae5503ef22439ca5dd394fd/library/std/src/sys/unix/thread.rs:71:17
  51:     0x7fdad5be0259 - start_thread
  52:     0x7fdad59be5e3 - __GI___clone
  53:                0x0 - <unknown>
```

My server main code looks like this:
```
#[tokio::main]
async fn main()  -> std::io::Result<()>{
    println!("Hello, world!");
    let socket = Arc::new(tokio::net::UdpSocket::bind("127.0.0.1:5000").await?);
    
    let (sender, receiver) = tokio::sync::mpsc::channel(100);
    let (mut udp_dispatcher, mut client_receiver) = UdpDispatcher::create(socket.clone(), sender);
    let mut udp_transmitter = UdpTransmitter{tx_receiver: receiver, socket: socket};

    tokio::spawn(async move {
            // Process each socket concurrently.
            udp_dispatcher.handle_rx().await
        });

    tokio::spawn(async move {
            // Process each socket concurrently.
            udp_transmitter.handle_tx().await
        });

    let mut acceptor = SslAcceptor::mozilla_intermediate(SslMethod::dtls()).unwrap();
    acceptor.set_private_key_file("../../certs/server_key.pem", SslFiletype::PEM).unwrap();
    acceptor.set_certificate_chain_file("../../certs/server_crt.pem").unwrap();
    acceptor.check_private_key().unwrap();
    let acceptor = Arc::new(acceptor.build());
    
    loop
    {
        if let Some(client) = client_receiver.recv().await
        {
            println!("new client {}", client.addr);
            let acceptor = acceptor.clone();
            thread::spawn(move || {
                let stream = acceptor.accept(client).unwrap();
                handle_client(stream);
            });
        }
    }
}
```

I think the crate should not cause a panic. this looks like a bug.

**Comment by rainerschoe** [comment]
I tried the same using [openssl](https://docs.rs/openssl/0.10.34/openssl/) crate, after I found out that the boring crate is a fork. It shows the same problem. I opened an issue [there](https://github.com/sfackler/rust-openssl/issues/1481) too.
Not sure how actively the boring crate is maintained anymore and how you are syncing with openssl crate, so leaving this open here too.

**Comment by rainerschoe** [comment]
This was user error (see openssl crate thread). closing
